#Requires -Version 5.1
<#
.SYNOPSIS
  Start Sales OS internal trial on Windows WITHOUT Docker.
  Isolated Postgres+Redis on 127.0.0.1 (default 15432/16379; configurable —
  user trial may use 55432/56379) + Node API + worker + static gateway.
  Gates on GET http://127.0.0.1:NATIVE_WEB_PORT/api/health (ok + sales-os-api),
  Redis 5+, worker alive. API_HOST forced to 127.0.0.1 (loopback-only).
  Never prints secret values. Never reuses 5432/6379. Never overwrites foreign data.
#>
$ErrorActionPreference = "Stop"
$Root = (Resolve-Path (Join-Path $PSScriptRoot "..\..\..")).Path
Set-Location $Root
. (Join-Path $PSScriptRoot "NativeCommon.ps1")

# Override Fail to cleanup processes we started on this run
function Fail([string]$Msg) {
  Write-Host "FAIL: $Msg" -ForegroundColor Red
  if ($script:StartedSomething) {
    Write-Host "Cleaning up processes started by this script..." -ForegroundColor Yellow
    try { & (Join-Path $PSScriptRoot "Stop-InternalTrial-Native.ps1") } catch { }
  }
  exit 1
}

$NativeDir = Join-Path $Root "scripts\windows\native"
$DataRoot = Join-Path $Root ".data\native"
$PgData = Join-Path $DataRoot "pg"
$RedisData = Join-Path $DataRoot "redis"
$RunDir = Join-Path $DataRoot "run"
$LogDir = Join-Path $DataRoot "logs"
$VendorWin = Join-Path $Root "vendor\windows"
$EnvFile = Join-Path $Root ".env.native"
$MarkerFile = Join-Path $DataRoot "SALES_OS_NATIVE_TRIAL.marker"
$script:StartedSomething = $false

function Invoke-FailureCleanup {
  Write-Host "Cleaning up processes started by this script..." -ForegroundColor Yellow
  try {
    & (Join-Path $NativeDir "Stop-InternalTrial-Native.ps1")
  } catch {
    Write-Host "WARN: cleanup Stop failed: $($_.Exception.Message)"
  }
}

function New-RandomSecret([int]$Bytes = 24) {
  $buf = New-Object byte[] $Bytes
  [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($buf)
  return [Convert]::ToBase64String($buf).TrimEnd('=') -replace '[+/]', 'A'
}

function Test-PortFree([int]$Port) {
  try {
    $listeners = Get-NetTCPConnection -State Listen -ErrorAction SilentlyContinue |
      Where-Object { $_.LocalPort -eq $Port }
    if ($listeners) { return $false }
  } catch { }
  try {
    $tcp = New-Object System.Net.Sockets.TcpListener([System.Net.IPAddress]::Loopback, $Port)
    $tcp.Start(); $tcp.Stop(); return $true
  } catch {
    return $false
  }
}

function Assert-PortFree([int]$Port, [string]$Label) {
  if (Test-PortFree $Port) { return }
  Fail "port-collision: $Label port $Port is already in use. Choose another NATIVE_*_PORT in .env.native (never reuse Sub2API 5432/6379). Example alternate pair used in trial: 55432/56379."
}

function Find-PgBin([string]$Name) {
  $cands = @(
    (Join-Path $VendorWin "pgsql\bin\$Name.exe"),
    (Join-Path $VendorWin "pgsql\bin\$Name")
  )
  foreach ($c in $cands) { if (Test-Path -LiteralPath $c) { return $c } }
  $cmd = Get-Command $Name -ErrorAction SilentlyContinue
  if ($cmd) { return $cmd.Source }
  return $null
}

function Find-RedisServer() {
  # Prefer project vendor (Redis 5+) over PATH (may be ancient 3.0.x)
  $cands = @(
    (Join-Path $VendorWin "redis\redis-server.exe"),
    (Join-Path $VendorWin "Redis\redis-server.exe")
  )
  foreach ($c in $cands) { if (Test-Path -LiteralPath $c) { return $c } }
  $cmd = Get-Command "redis-server" -ErrorAction SilentlyContinue
  if ($cmd) { return $cmd.Source }
  return $null
}

function Quote-RedisConfPath([string]$Path) {
  # Redis conf: quote paths that contain spaces
  $fwd = ($Path -replace '\\', '/')
  if ($fwd -match '\s') { return "`"$fwd`"" }
  return $fwd
}

if (-not (Get-Command node -ErrorAction SilentlyContinue)) {
  Fail "node-missing: Install Node.js 20+ LTS (or Node 24.x) from https://nodejs.org/ then re-open PowerShell. Official MSI includes npm."
}
if (-not (Get-Command npm -ErrorAction SilentlyContinue)) {
  Fail "npm-missing: Node.js install incomplete (npm not on PATH). Install official Node MSI (includes npm), then re-open PowerShell."
}

# --- Ensure .env.native ---
if (-not (Test-Path -LiteralPath $EnvFile)) {
  $pgPass = New-RandomSecret 18
  $jwt = New-RandomSecret 32
  $demo = New-RandomSecret 12
  @"
# Generated by Start-InternalTrial-Native.ps1 — DO NOT COMMIT
NATIVE_PG_PORT=15432
NATIVE_REDIS_PORT=16379
NATIVE_API_PORT=39300
NATIVE_WEB_PORT=19280
# Loopback-only API bind (native). Docker leaves API_HOST unset → 0.0.0.0
API_HOST=127.0.0.1
POSTGRES_USER=sales
POSTGRES_PASSWORD=$pgPass
POSTGRES_DB=sales_os
JWT_SECRET=$jwt
SEED_ON_BOOT=true
DEMO_AGENT_PASSWORD=$demo
DEMO_AGENT2_PASSWORD=$demo
DEMO_ADMIN_PASSWORD=$demo
DEMO_MANAGER_PASSWORD=$demo
DEMO_VIEWER_PASSWORD=$demo
DEMO_TENANT_SLUG=demo
REAL_SMS_ENABLED=false
REAL_CALL_ENABLED=false
REAL_EMAIL_ENABLED=false
"@ | Set-Content -LiteralPath $EnvFile -Encoding UTF8
  Write-Host "Created .env.native with random local secrets (not printed)." -ForegroundColor Yellow
}

$envMap = Parse-DotEnv $EnvFile
$required = @(
  "POSTGRES_PASSWORD", "JWT_SECRET",
  "DEMO_AGENT_PASSWORD", "DEMO_AGENT2_PASSWORD",
  "DEMO_ADMIN_PASSWORD", "DEMO_MANAGER_PASSWORD", "DEMO_VIEWER_PASSWORD"
)
$bad = @()
foreach ($k in $required) {
  if (-not $envMap.ContainsKey($k)) { $bad += $k; continue }
  $v = $envMap[$k]
  if ([string]::IsNullOrWhiteSpace($v) -or $v -eq "CHANGE_ME") { $bad += $k }
}
if ($bad.Count -gt 0) {
  Fail ("Required .env.native keys empty or CHANGE_ME: " + ($bad -join ", "))
}

function PortOrDefault([string]$Key, [int]$Default) {
  if ($envMap.ContainsKey($Key) -and $envMap[$Key] -match '^\d+$') { return [int]$envMap[$Key] }
  return $Default
}

$PgPort = PortOrDefault "NATIVE_PG_PORT" 15432
$RedisPort = PortOrDefault "NATIVE_REDIS_PORT" 16379
$ApiPort = PortOrDefault "NATIVE_API_PORT" 39300
$WebPort = PortOrDefault "NATIVE_WEB_PORT" 19280
# Native MUST loopback-only
$ApiHost = "127.0.0.1"

if ($PgPort -eq 5432 -or $RedisPort -eq 6379) {
  Fail "refusing default Sub2API ports: set NATIVE_PG_PORT/NATIVE_REDIS_PORT to dedicated values (e.g. 15432/16379 or 55432/56379)."
}

$PgUser = if ($envMap.ContainsKey("POSTGRES_USER")) { $envMap["POSTGRES_USER"] } else { "sales" }
$PgDb = if ($envMap.ContainsKey("POSTGRES_DB")) { $envMap["POSTGRES_DB"] } else { "sales_os" }
$PgPass = $envMap["POSTGRES_PASSWORD"]

# --- Protect foreign data dirs ---
New-Item -ItemType Directory -Force -Path $DataRoot, $RunDir, $LogDir | Out-Null
if (-not (Test-PathUnderRoot -Candidate $DataRoot -Root $Root)) {
  Fail "data-dir-escape: .data/native resolved outside project root — refusing."
}
if (Test-Path -LiteralPath $PgData) {
  if (-not (Test-Path -LiteralPath $MarkerFile)) {
    Fail "data-dir-foreign: .data/native exists without SALES_OS_NATIVE_TRIAL.marker — refusing to overwrite. Move/rename the folder or create the marker only if you own this trial data."
  }
} else {
  New-Item -ItemType Directory -Force -Path $PgData | Out-Null
  "sales-os-native-trial" | Set-Content -LiteralPath $MarkerFile -Encoding UTF8
}
if (-not (Test-Path -LiteralPath $RedisData)) { New-Item -ItemType Directory -Force -Path $RedisData | Out-Null }
if (-not (Test-Path -LiteralPath $MarkerFile)) {
  "sales-os-native-trial" | Set-Content -LiteralPath $MarkerFile -Encoding UTF8
}

# Idempotent Start: stop prior owned run first (safe Stop verifies ownership)
if (Test-Path -LiteralPath (Join-Path $RunDir "api.pid") -or
    Test-Path -LiteralPath (Join-Path $RunDir "gateway.pid") -or
    Test-Path -LiteralPath (Join-Path $RunDir "worker.pid") -or
    Test-Path -LiteralPath (Join-Path $RunDir "redis.pid")) {
  Write-Host "Prior native PID files found — stopping owned processes before re-start..."
  & (Join-Path $NativeDir "Stop-InternalTrial-Native.ps1")
  Start-Sleep -Seconds 2
}

$initdb = Find-PgBin "initdb"
$pgCtl = Find-PgBin "pg_ctl"
$psql = Find-PgBin "psql"
$pgIsReady = Find-PgBin "pg_isready"
$redisServer = Find-RedisServer

if (-not $initdb -or -not $pgCtl -or -not $psql) {
  Fail @"
postgres-binaries-missing: initdb/pg_ctl/psql not found on PATH or vendor\windows\pgsql\bin.
Run: .\scripts\windows\native\Fetch-NativeDeps.ps1
Or install PostgreSQL 15/16/17 from https://www.postgresql.org/download/windows/ and add its bin to PATH
(then still use dedicated ports — do not point at Sub2API data dirs).
"@
}
if (-not $redisServer) {
  Fail @"
redis-binaries-missing: redis-server not found under vendor\windows\redis\ (preferred) or PATH.
Worker needs Redis 5+ (streams). Run: .\scripts\windows\native\Fetch-NativeDeps.ps1
(tporadowski Redis 5.0.14.1). Do not use Redis 3.0.x. Do not touch other Redis services.
"@
}

Assert-PortFree $PgPort "Postgres"
Assert-PortFree $RedisPort "Redis"
Assert-PortFree $ApiPort "API"
Assert-PortFree $WebPort "Web"

try {

# --- Init Postgres if needed ---
$PgVersionFile = Join-Path $PgData "PG_VERSION"
if (-not (Test-Path -LiteralPath $PgVersionFile)) {
  Write-Host "Initializing isolated Postgres data dir (.data/native/pg)..."
  $pwFile = Join-Path $RunDir "pg_pw.txt"
  $PgPass | Set-Content -LiteralPath $pwFile -Encoding ASCII
  # PowerShell passes args as argv — quote-safe for paths with spaces
  & $initdb @('-D', $PgData, '-U', $PgUser, '-A', 'password', "--pwfile=$pwFile", '-E', 'UTF8', '--locale=C') 2>&1 | Out-Null
  if ($LASTEXITCODE -ne 0) { Fail "initdb failed (exit $LASTEXITCODE)" }
  Remove-Item -LiteralPath $pwFile -Force -ErrorAction SilentlyContinue
  $conf = Join-Path $PgData "postgresql.conf"
  Add-Content -LiteralPath $conf -Value "`nlisten_addresses = '127.0.0.1'`nport = $PgPort`n"
  $hba = Join-Path $PgData "pg_hba.conf"
  @"
# sales-os native trial — local only
host all all 127.0.0.1/32 scram-sha-256
host all all ::1/128 scram-sha-256
local all all scram-sha-256
"@ | Set-Content -LiteralPath $hba -Encoding ASCII
}

# --- Start Postgres ---
Write-Host "Starting Postgres on 127.0.0.1:$PgPort ..."
$pgLog = Join-Path $LogDir "postgres.log"
& $pgCtl @('-D', $PgData, '-l', $pgLog, '-o', "-p $PgPort -h 127.0.0.1", 'start') 2>&1 | Out-Null
if ($LASTEXITCODE -ne 0) {
  & $pgCtl @('-D', $PgData, 'status') 2>&1 | Out-Null
  if ($LASTEXITCODE -ne 0) { Fail "postgres-start-failed (see .data/native/logs/postgres.log)" }
}
$script:StartedSomething = $true

if (-not (Wait-TcpAccept -HostName "127.0.0.1" -Port $PgPort -TimeoutSec 60 -Label "Postgres")) {
  Fail "postgres-not-ready: TCP 127.0.0.1:$PgPort did not accept within 60s"
}
if ($pgIsReady) {
  & $pgIsReady -h 127.0.0.1 -p $PgPort -U $PgUser 2>&1 | Out-Null
}

$env:PGPASSWORD = $PgPass
$dbCheck = & $psql -h 127.0.0.1 -p $PgPort -U $PgUser -d postgres -tAc "SELECT 1 FROM pg_database WHERE datname='$PgDb'"
if ("$dbCheck".Trim() -ne "1") {
  & $psql -h 127.0.0.1 -p $PgPort -U $PgUser -d postgres -c "CREATE DATABASE $PgDb OWNER $PgUser;" | Out-Null
}
Remove-Item Env:PGPASSWORD -ErrorAction SilentlyContinue

# --- Start Redis (loopback), quote paths with spaces ---
Write-Host "Starting Redis on 127.0.0.1:$RedisPort ..."
$redisConf = Join-Path $RunDir "redis.conf"
$dirLine = "dir " + (Quote-RedisConfPath $RedisData)
@"
bind 127.0.0.1
port $RedisPort
$dirLine
appendonly yes
protected-mode yes
"@ | Set-Content -LiteralPath $redisConf -Encoding ASCII

$redisOut = Join-Path $LogDir "redis.out.log"
$redisErr = Join-Path $LogDir "redis.err.log"
$redisPidFile = Join-Path $RunDir "redis.pid"
# Quote conf path for ArgumentList when spaces present
$null = Start-LoggedProcess -FilePath $redisServer -ArgumentList @($redisConf) `
  -WorkingDirectory (Split-Path -Parent $redisServer) `
  -OutLog $redisOut -ErrLog $redisErr -PidFile $redisPidFile

$redisCli = Find-RedisCliNear $redisServer
$redisReady = $false
$deadlineRedis = (Get-Date).AddSeconds(30)
while ((Get-Date) -lt $deadlineRedis) {
  if ($redisCli -and (Invoke-RedisPing -RedisCli $redisCli -HostName "127.0.0.1" -Port $RedisPort)) {
    $redisReady = $true
    break
  }
  if (-not $redisCli) {
    if (Wait-TcpAccept -HostName "127.0.0.1" -Port $RedisPort -TimeoutSec 1) {
      # TCP up but no cli — still try version via server binary later
      $redisReady = $true
      break
    }
  }
  Start-Sleep -Milliseconds 500
}
if (-not $redisReady) {
  Fail "redis-not-ready: PING/TCP failed on 127.0.0.1:$RedisPort (see .data/native/logs/redis.*.log)"
}

$redisVer = Get-RedisVersionString -RedisCli $redisCli -Host "127.0.0.1" -Port $RedisPort -RedisServerPath $redisServer
Write-Host "Redis version: $redisVer"
Assert-RedisVersionOk -Version $redisVer -MinMajor 5

# --- Node deps / build ---
if (-not (Test-Path -LiteralPath (Join-Path $Root "node_modules"))) {
  Write-Host "npm ci (first run)..."
  npm ci
  if ($LASTEXITCODE -ne 0) { npm install; if ($LASTEXITCODE -ne 0) { Fail "npm-install-failed" } }
}
$apiMain = Join-Path $Root "apps\api\dist\main.js"
$workerMain = Join-Path $Root "apps\worker\dist\main.js"
$webDist = Join-Path $Root "apps\web\dist\index.html"
if (-not (Test-Path -LiteralPath $apiMain) -or -not (Test-Path -LiteralPath $workerMain) -or -not (Test-Path -LiteralPath $webDist)) {
  Write-Host "Building API/worker/web..."
  npm run build
  if ($LASTEXITCODE -ne 0) { Fail "npm-build-failed" }
}

$DatabaseUrl = "postgres://${PgUser}:${PgPass}@127.0.0.1:${PgPort}/${PgDb}"
$RedisUrl = "redis://127.0.0.1:${RedisPort}"

$raw = Get-Content -LiteralPath $EnvFile -Raw -Encoding UTF8
if ($raw -notmatch '(?m)^DATABASE_URL=') { $raw += "`nDATABASE_URL=$DatabaseUrl`n" }
else { $raw = [regex]::Replace($raw, '(?m)^DATABASE_URL=.*$', "DATABASE_URL=$DatabaseUrl") }
if ($raw -notmatch '(?m)^REDIS_URL=') { $raw += "REDIS_URL=$RedisUrl`n" }
else { $raw = [regex]::Replace($raw, '(?m)^REDIS_URL=.*$', "REDIS_URL=$RedisUrl") }
if ($raw -notmatch '(?m)^API_HOST=') { $raw += "API_HOST=127.0.0.1`n" }
else { $raw = [regex]::Replace($raw, '(?m)^API_HOST=.*$', "API_HOST=127.0.0.1") }
Set-Content -LiteralPath $EnvFile -Value $raw -Encoding UTF8

$nodeExe = (Get-Command node).Source
$commonNodeEnv = @{
  DATABASE_URL = $DatabaseUrl
  REDIS_URL = $RedisUrl
  JWT_SECRET = $envMap["JWT_SECRET"]
  API_HOST = $ApiHost
  API_PORT = "$ApiPort"
  PORT = "$ApiPort"
  SEED_ON_BOOT = if ($envMap.ContainsKey("SEED_ON_BOOT")) { $envMap["SEED_ON_BOOT"] } else { "true" }
  DEMO_AGENT_PASSWORD = $envMap["DEMO_AGENT_PASSWORD"]
  DEMO_AGENT2_PASSWORD = $envMap["DEMO_AGENT2_PASSWORD"]
  DEMO_ADMIN_PASSWORD = $envMap["DEMO_ADMIN_PASSWORD"]
  DEMO_MANAGER_PASSWORD = $envMap["DEMO_MANAGER_PASSWORD"]
  DEMO_VIEWER_PASSWORD = $envMap["DEMO_VIEWER_PASSWORD"]
  DEMO_TENANT_SLUG = if ($envMap.ContainsKey("DEMO_TENANT_SLUG")) { $envMap["DEMO_TENANT_SLUG"] } else { "demo" }
  REAL_SMS_ENABLED = "false"
  REAL_CALL_ENABLED = "false"
  REAL_EMAIL_ENABLED = "false"
  NODE_ENV = "production"
}

# --- Start API (loopback) ---
Write-Host "Starting API on ${ApiHost}:$ApiPort (API_HOST=$ApiHost) ..."
$apiOut = Join-Path $LogDir "api.out.log"
$apiErr = Join-Path $LogDir "api.err.log"
$null = Start-LoggedProcess -FilePath $nodeExe -ArgumentList @($apiMain) `
  -WorkingDirectory $Root -EnvMap $commonNodeEnv `
  -OutLog $apiOut -ErrLog $apiErr -PidFile (Join-Path $RunDir "api.pid")

# --- Start worker ---
Write-Host "Starting worker..."
$workerOut = Join-Path $LogDir "worker.out.log"
$workerErr = Join-Path $LogDir "worker.err.log"
$workerEnv = @{
  DATABASE_URL = $DatabaseUrl
  REDIS_URL = $RedisUrl
  NODE_ENV = "production"
}
$null = Start-LoggedProcess -FilePath $nodeExe -ArgumentList @($workerMain) `
  -WorkingDirectory $Root -EnvMap $workerEnv `
  -OutLog $workerOut -ErrLog $workerErr -PidFile (Join-Path $RunDir "worker.pid")

# --- Start gateway ---
Write-Host "Starting web gateway on 127.0.0.1:$WebPort ..."
$gwOut = Join-Path $LogDir "gateway.out.log"
$gwErr = Join-Path $LogDir "gateway.err.log"
$gwMain = Join-Path $Root "deploy\public-gateway.mjs"
$gwEnv = @{
  GATEWAY_HOST = "127.0.0.1"
  GATEWAY_PORT = "$WebPort"
  API_TARGET = "http://${ApiHost}:$ApiPort"
  GATEWAY_WEB_MODE = "static"
}
$null = Start-LoggedProcess -FilePath $nodeExe -ArgumentList @($gwMain) `
  -WorkingDirectory $Root -EnvMap $gwEnv `
  -OutLog $gwOut -ErrLog $gwErr -PidFile (Join-Path $RunDir "gateway.pid")

# --- Wait API health (direct) ---
$apiHealthUrl = "http://${ApiHost}:$ApiPort/health"
$apiOk = $false
$deadlineApi = (Get-Date).AddSeconds(90)
Write-Host "Waiting for API health: $apiHealthUrl"
while ((Get-Date) -lt $deadlineApi) {
  try {
    $resp = Invoke-WebRequest -Uri $apiHealthUrl -UseBasicParsing -TimeoutSec 5 -ErrorAction Stop
    if ([int]$resp.StatusCode -ge 200 -and [int]$resp.StatusCode -lt 300 -and (Test-ApiHealthJson ([string]$resp.Content))) {
      $apiOk = $true
      break
    }
  } catch { }
  if (Test-LogLooksFatal $apiErr) { break }
  Start-Sleep -Seconds 2
}
if (-not $apiOk) {
  Fail "api-or-db-not-ready: API health gate failed (see .data/native/logs/api.*.log)"
}

# --- Wait worker ---
$workerOk = $false
$deadlineWorker = (Get-Date).AddSeconds(45)
Write-Host "Waiting for worker (process + log readiness)..."
while ((Get-Date) -lt $deadlineWorker) {
  $wPidText = Get-Content -LiteralPath (Join-Path $RunDir "worker.pid") -ErrorAction SilentlyContinue | Select-Object -First 1
  $alive = $false
  if ($wPidText -match '^\d+$') {
    try { if (Get-Process -Id ([int]$wPidText) -ErrorAction SilentlyContinue) { $alive = $true } } catch { }
  }
  if ($alive -and (Test-WorkerReadyFromLog $workerOut)) { $workerOk = $true; break }
  if ($alive -and -not (Test-LogLooksFatal $workerErr)) {
    # Soft ready: process alive + redis PING + no fatal after a few seconds
    $elapsed = ((Get-Date) - ($deadlineWorker.AddSeconds(-45))).TotalSeconds
    if ($elapsed -ge 8 -and $redisCli -and (Invoke-RedisPing -RedisCli $redisCli -HostName "127.0.0.1" -Port $RedisPort)) {
      $workerOk = $true
      break
    }
  }
  if (Test-LogLooksFatal $workerErr) { break }
  Start-Sleep -Seconds 1
}
if (-not $workerOk) {
  Fail "worker-not-ready: worker process/log check failed (see .data/native/logs/worker.*.log). Redis must be 5+ for XGROUP."
}

# --- Health gate via web ---
$healthUrl = "http://127.0.0.1:$WebPort/api/health"
$deadline = (Get-Date).AddSeconds(60)
$passed = $false
$lastBody = $null
$lastStatus = $null
Write-Host "Waiting for web /api/health: $healthUrl"
while ((Get-Date) -lt $deadline) {
  try {
    $resp = Invoke-WebRequest -Uri $healthUrl -UseBasicParsing -TimeoutSec 5 -ErrorAction Stop
    $lastStatus = [int]$resp.StatusCode
    $lastBody = [string]$resp.Content
    if ($lastStatus -ge 200 -and $lastStatus -lt 300 -and (Test-ApiHealthJson $lastBody)) {
      $passed = $true
      break
    }
  } catch {
    $lastBody = $_.Exception.Message
    $lastStatus = $null
  }
  Start-Sleep -Seconds 2
}

if ($passed) {
  Write-Host ""
  Write-Host "OK. Browser: http://127.0.0.1:$WebPort" -ForegroundColor Green
  Write-Host "Health gate passed: GET $healthUrl (ok + sales-os-api)"
  Write-Host "Redis $redisVer OK (>=5). Worker PID recorded. API_HOST=$ApiHost"
  Write-Host "Logs: .data/native/logs/  PIDs: .data/native/run/"
  Write-Host "Demo emails: manager@demo.local / agent@demo.local / agent2@demo.local (passwords only in .env.native)"
  Write-Host "Stop: .\scripts\windows\native\Stop-InternalTrial-Native.ps1"
  exit 0
}

Write-Host ""
Write-Host "FAIL: api-or-db-not-ready — web /api/health gate did not pass" -ForegroundColor Red
Write-Host "URL: $healthUrl"
if ($null -ne $lastStatus) { Write-Host "Last HTTP: $lastStatus" } else { Write-Host "Last HTTP: (no response)" }
Write-Host "服务不可用。切勿当作已可用。"
Invoke-FailureCleanup
exit 1

} catch {
  Write-Host "FAIL: $($_.Exception.Message)" -ForegroundColor Red
  if ($script:StartedSomething) { Invoke-FailureCleanup }
  exit 1
}
