#Requires -Version 5.1
<#
.SYNOPSIS
  Start Sales OS internal trial on Windows WITHOUT Docker.
  Isolated Postgres+Redis on 127.0.0.1 (default 15432/16379) + Node API + static gateway.
  Gates on GET http://127.0.0.1:NATIVE_WEB_PORT/api/health (ok + sales-os-api).
  Never prints secret values. Never reuses default 5432/6379 if occupied by other apps —
  always uses dedicated ports. Never overwrites foreign data directories.
#>
$ErrorActionPreference = "Stop"
$Root = Resolve-Path (Join-Path $PSScriptRoot "..\..\..")
Set-Location $Root
$NativeDir = Join-Path $Root "scripts\windows\native"
$DataRoot = Join-Path $Root ".data\native"
$PgData = Join-Path $DataRoot "pg"
$RedisData = Join-Path $DataRoot "redis"
$RunDir = Join-Path $DataRoot "run"
$LogDir = Join-Path $DataRoot "logs"
$VendorWin = Join-Path $Root "vendor\windows"
$EnvFile = Join-Path $Root ".env.native"
$MarkerFile = Join-Path $DataRoot "SALES_OS_NATIVE_TRIAL.marker"

function Fail([string]$Msg) {
  Write-Host "FAIL: $Msg" -ForegroundColor Red
  exit 1
}

function Parse-DotEnv([string]$Path) {
  $map = @{}
  if (-not (Test-Path $Path)) { return $map }
  Get-Content -LiteralPath $Path -Encoding UTF8 | ForEach-Object {
    $line = $_.Trim()
    if ($line -eq "" -or $line.StartsWith("#")) { return }
    $eq = $line.IndexOf("=")
    if ($eq -lt 1) { return }
    $key = $line.Substring(0, $eq).Trim()
    $val = $line.Substring($eq + 1).Trim()
    if (($val.StartsWith('"') -and $val.EndsWith('"')) -or ($val.StartsWith("'") -and $val.EndsWith("'"))) {
      if ($val.Length -ge 2) { $val = $val.Substring(1, $val.Length - 2) }
    }
    if ($key -ne "") { $map[$key] = $val }
  }
  return $map
}

function New-RandomSecret([int]$Bytes = 24) {
  $buf = New-Object byte[] $Bytes
  [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($buf)
  return [Convert]::ToBase64String($buf).TrimEnd('=') -replace '[+/]', 'A'
}

function Test-ApiHealthJson([string]$Body) {
  if ([string]::IsNullOrWhiteSpace($Body)) { return $false }
  $trim = $Body.TrimStart()
  if (-not ($trim.StartsWith("{") -or $trim.StartsWith("["))) { return $false }
  try { $j = $Body | ConvertFrom-Json -ErrorAction Stop } catch { return $false }
  $ok = $false
  if ($null -ne $j.ok) {
    if ($j.ok -is [bool]) { $ok = [bool]$j.ok }
    elseif ("$($j.ok)" -eq "True" -or "$($j.ok)" -eq "true" -or "$($j.ok)" -eq "1") { $ok = $true }
  }
  $svc = ""
  if ($null -ne $j.service) { $svc = [string]$j.service }
  return ($ok -and $svc -eq "sales-os-api")
}

function Test-PortFree([int]$Port) {
  $listeners = Get-NetTCPConnection -State Listen -ErrorAction SilentlyContinue |
    Where-Object { $_.LocalPort -eq $Port }
  if ($listeners) { return $false }
  # Fallback for older PS without Get-NetTCPConnection
  try {
    $tcp = New-Object System.Net.Sockets.TcpListener([System.Net.IPAddress]::Loopback, $Port)
    $tcp.Start(); $tcp.Stop(); return $true
  } catch {
    return $false
  }
}

function Assert-PortFreeOrOurs([int]$Port, [string]$Label) {
  if (Test-PortFree $Port) { return }
  # If our pid files claim it, allow restart path to stop first
  Fail "port-collision: $Label port $Port is already in use on this machine. Choose another NATIVE_*_PORT in .env.native (never reuse Sub2API 5432/6379)."
}

function Find-PgBin([string]$Name) {
  $cmd = Get-Command $Name -ErrorAction SilentlyContinue
  if ($cmd) { return $cmd.Source }
  $cands = @(
    (Join-Path $VendorWin "pgsql\bin\$Name.exe"),
    (Join-Path $VendorWin "pgsql\bin\$Name")
  )
  foreach ($c in $cands) { if (Test-Path $c) { return $c } }
  return $null
}

function Find-RedisServer() {
  $cmd = Get-Command "redis-server" -ErrorAction SilentlyContinue
  if ($cmd) { return $cmd.Source }
  $cands = @(
    (Join-Path $VendorWin "redis\redis-server.exe"),
    (Join-Path $VendorWin "Redis\redis-server.exe")
  )
  foreach ($c in $cands) { if (Test-Path $c) { return $c } }
  return $null
}

if (-not (Get-Command node -ErrorAction SilentlyContinue)) {
  Fail "node-missing: Install Node.js 20+ LTS from https://nodejs.org/ then re-open PowerShell."
}
if (-not (Get-Command npm -ErrorAction SilentlyContinue)) {
  Fail "npm-missing: Node.js install incomplete (npm not on PATH)."
}

# --- Ensure .env.native ---
if (-not (Test-Path $EnvFile)) {
  $example = Join-Path $NativeDir ".env.native.example"
  $pgPass = New-RandomSecret 18
  $jwt = New-RandomSecret 32
  $demo = New-RandomSecret 12
  @"
# Generated by Start-InternalTrial-Native.ps1 — DO NOT COMMIT
NATIVE_PG_PORT=15432
NATIVE_REDIS_PORT=16379
NATIVE_API_PORT=39300
NATIVE_WEB_PORT=19280
POSTGRES_USER=sales
POSTGRES_PASSWORD=$pgPass
POSTGRES_DB=sales_os
JWT_SECRET=$jwt
SEED_ON_BOOT=true
DEMO_AGENT_PASSWORD=$demo
DEMO_AGENT2_PASSWORD=$demo
DEMO_ADMIN_PASSWORD=$demo
DEMO_MANAGER_PASSWORD=$demo
DEMO_VIEWER_PASSWORD=$demo
DEMO_TENANT_SLUG=demo
REAL_SMS_ENABLED=false
REAL_CALL_ENABLED=false
REAL_EMAIL_ENABLED=false
"@ | Set-Content -LiteralPath $EnvFile -Encoding UTF8
  Write-Host "Created .env.native with random local secrets (not printed)." -ForegroundColor Yellow
}

$envMap = Parse-DotEnv $EnvFile
$required = @(
  "POSTGRES_PASSWORD", "JWT_SECRET",
  "DEMO_AGENT_PASSWORD", "DEMO_AGENT2_PASSWORD",
  "DEMO_ADMIN_PASSWORD", "DEMO_MANAGER_PASSWORD", "DEMO_VIEWER_PASSWORD"
)
$bad = @()
foreach ($k in $required) {
  if (-not $envMap.ContainsKey($k)) { $bad += $k; continue }
  $v = $envMap[$k]
  if ([string]::IsNullOrWhiteSpace($v) -or $v -eq "CHANGE_ME") { $bad += $k }
}
if ($bad.Count -gt 0) {
  Fail ("Required .env.native keys empty or CHANGE_ME: " + ($bad -join ", "))
}

function PortOrDefault([string]$Key, [int]$Default) {
  if ($envMap.ContainsKey($Key) -and $envMap[$Key] -match '^\d+$') { return [int]$envMap[$Key] }
  return $Default
}

$PgPort = PortOrDefault "NATIVE_PG_PORT" 15432
$RedisPort = PortOrDefault "NATIVE_REDIS_PORT" 16379
$ApiPort = PortOrDefault "NATIVE_API_PORT" 39300
$WebPort = PortOrDefault "NATIVE_WEB_PORT" 19280

# Hard refuse classic Sub2API defaults unless explicitly overridden AND free —
# still warn: we never bind to 5432/6379 by default.
if ($PgPort -eq 5432 -or $RedisPort -eq 6379) {
  Fail "refusing default Sub2API ports: set NATIVE_PG_PORT/NATIVE_REDIS_PORT to dedicated values (e.g. 15432/16379)."
}

$PgUser = if ($envMap.ContainsKey("POSTGRES_USER")) { $envMap["POSTGRES_USER"] } else { "sales" }
$PgDb = if ($envMap.ContainsKey("POSTGRES_DB")) { $envMap["POSTGRES_DB"] } else { "sales_os" }
$PgPass = $envMap["POSTGRES_PASSWORD"]

# --- Protect foreign data dirs ---
New-Item -ItemType Directory -Force -Path $DataRoot, $RunDir, $LogDir | Out-Null
if (Test-Path $PgData) {
  if (-not (Test-Path $MarkerFile)) {
    Fail "data-dir-foreign: .data/native exists without SALES_OS_NATIVE_TRIAL.marker — refusing to overwrite. Move/rename the folder or create the marker only if you own this trial data."
  }
} else {
  New-Item -ItemType Directory -Force -Path $PgData | Out-Null
  "sales-os-native-trial" | Set-Content -LiteralPath $MarkerFile -Encoding UTF8
}
if (-not (Test-Path $RedisData)) { New-Item -ItemType Directory -Force -Path $RedisData | Out-Null }
if (-not (Test-Path $MarkerFile)) {
  "sales-os-native-trial" | Set-Content -LiteralPath $MarkerFile -Encoding UTF8
}

$initdb = Find-PgBin "initdb"
$pgCtl = Find-PgBin "pg_ctl"
$psql = Find-PgBin "psql"
$postgres = Find-PgBin "postgres"
$redisServer = Find-RedisServer

if (-not $initdb -or -not $pgCtl -or -not $psql) {
  Fail @"
postgres-binaries-missing: initdb/pg_ctl/psql not found on PATH or vendor\windows\pgsql\bin.
Run: .\scripts\windows\native\Fetch-NativeDeps.ps1
Or install PostgreSQL from https://www.postgresql.org/download/windows/ and add its bin to PATH
(then still use dedicated ports 15432/16379 — do not point at Sub2API data dirs).
"@
}
if (-not $redisServer) {
  Fail @"
redis-binaries-missing: redis-server not found on PATH or vendor\windows\redis\.
Run: .\scripts\windows\native\Fetch-NativeDeps.ps1
Or place tporadowski Redis redis-server.exe under vendor\windows\redis\
"@
}

Assert-PortFreeOrOurs $PgPort "Postgres"
Assert-PortFreeOrOurs $RedisPort "Redis"
Assert-PortFreeOrOurs $ApiPort "API"
Assert-PortFreeOrOurs $WebPort "Web"

# --- Init Postgres if needed ---
$PgVersionFile = Join-Path $PgData "PG_VERSION"
if (-not (Test-Path $PgVersionFile)) {
  Write-Host "Initializing isolated Postgres data dir (.data/native/pg)..."
  $pwFile = Join-Path $RunDir "pg_pw.txt"
  $PgPass | Set-Content -LiteralPath $pwFile -Encoding ASCII
  & $initdb -D $PgData -U $PgUser -A password --pwfile=$pwFile -E UTF8 --locale=C 2>&1 | Out-Null
  if ($LASTEXITCODE -ne 0) { Fail "initdb failed (exit $LASTEXITCODE)" }
  Remove-Item -LiteralPath $pwFile -Force -ErrorAction SilentlyContinue
  # Loopback-only listen
  $conf = Join-Path $PgData "postgresql.conf"
  Add-Content -LiteralPath $conf -Value "`nlisten_addresses = '127.0.0.1'`nport = $PgPort`n"
  $hba = Join-Path $PgData "pg_hba.conf"
  @"
# sales-os native trial — local only
host all all 127.0.0.1/32 scram-sha-256
host all all ::1/128 scram-sha-256
local all all scram-sha-256
"@ | Set-Content -LiteralPath $hba -Encoding ASCII
}

# --- Start Postgres ---
Write-Host "Starting Postgres on 127.0.0.1:$PgPort ..."
$pgLog = Join-Path $LogDir "postgres.log"
& $pgCtl -D $PgData -l $pgLog -o "-p $PgPort -h 127.0.0.1" start 2>&1 | Out-Null
if ($LASTEXITCODE -ne 0) {
  # may already be running from prior native start
  & $pgCtl -D $PgData status 2>&1 | Out-Null
  if ($LASTEXITCODE -ne 0) { Fail "postgres-start-failed (see .data/native/logs/postgres.log)" }
}
# Create DB if missing
$env:PGPASSWORD = $PgPass
& $psql -h 127.0.0.1 -p $PgPort -U $PgUser -d postgres -tAc "SELECT 1 FROM pg_database WHERE datname='$PgDb'" 2>$null | Out-Null
$dbCheck = & $psql -h 127.0.0.1 -p $PgPort -U $PgUser -d postgres -tAc "SELECT 1 FROM pg_database WHERE datname='$PgDb'"
if ("$dbCheck".Trim() -ne "1") {
  & $psql -h 127.0.0.1 -p $PgPort -U $PgUser -d postgres -c "CREATE DATABASE $PgDb OWNER $PgUser;" | Out-Null
}
Remove-Item Env:PGPASSWORD -ErrorAction SilentlyContinue

# --- Start Redis (loopback) ---
Write-Host "Starting Redis on 127.0.0.1:$RedisPort ..."
$redisConf = Join-Path $RunDir "redis.conf"
@"
bind 127.0.0.1
port $RedisPort
dir $( $RedisData -replace '\\','/' )
appendonly yes
protected-mode yes
"@ | Set-Content -LiteralPath $redisConf -Encoding ASCII
$redisOut = Join-Path $LogDir "redis.out.log"
$redisErr = Join-Path $LogDir "redis.err.log"
$redisProc = Start-Process -FilePath $redisServer -ArgumentList @($redisConf) `
  -RedirectStandardOutput $redisOut -RedirectStandardError $redisErr -PassThru -WindowStyle Hidden
$redisProc.Id | Set-Content -LiteralPath (Join-Path $RunDir "redis.pid") -Encoding ASCII

# --- Node deps / build ---
if (-not (Test-Path (Join-Path $Root "node_modules"))) {
  Write-Host "npm ci (first run)..."
  npm ci
  if ($LASTEXITCODE -ne 0) { npm install; if ($LASTEXITCODE -ne 0) { Fail "npm-install-failed" } }
}
if (-not (Test-Path (Join-Path $Root "apps\api\dist\main.js"))) {
  Write-Host "Building API/web/worker..."
  npm run build
  if ($LASTEXITCODE -ne 0) { Fail "npm-build-failed" }
}

$DatabaseUrl = "postgres://${PgUser}:${PgPass}@127.0.0.1:${PgPort}/${PgDb}"
$RedisUrl = "redis://127.0.0.1:${RedisPort}"

# Refresh derived URLs into .env.native without echoing secrets
$raw = Get-Content -LiteralPath $EnvFile -Raw -Encoding UTF8
if ($raw -notmatch '(?m)^DATABASE_URL=') { $raw += "`nDATABASE_URL=$DatabaseUrl`n" }
else { $raw = [regex]::Replace($raw, '(?m)^DATABASE_URL=.*$', "DATABASE_URL=$DatabaseUrl") }
if ($raw -notmatch '(?m)^REDIS_URL=') { $raw += "REDIS_URL=$RedisUrl`n" }
else { $raw = [regex]::Replace($raw, '(?m)^REDIS_URL=.*$', "REDIS_URL=$RedisUrl") }
Set-Content -LiteralPath $EnvFile -Value $raw -Encoding UTF8

# --- Start API ---
Write-Host "Starting API on 127.0.0.1:$ApiPort ..."
$apiEnv = @{
  DATABASE_URL = $DatabaseUrl
  REDIS_URL = $RedisUrl
  JWT_SECRET = $envMap["JWT_SECRET"]
  API_PORT = "$ApiPort"
  PORT = "$ApiPort"
  SEED_ON_BOOT = if ($envMap.ContainsKey("SEED_ON_BOOT")) { $envMap["SEED_ON_BOOT"] } else { "true" }
  DEMO_AGENT_PASSWORD = $envMap["DEMO_AGENT_PASSWORD"]
  DEMO_AGENT2_PASSWORD = $envMap["DEMO_AGENT2_PASSWORD"]
  DEMO_ADMIN_PASSWORD = $envMap["DEMO_ADMIN_PASSWORD"]
  DEMO_MANAGER_PASSWORD = $envMap["DEMO_MANAGER_PASSWORD"]
  DEMO_VIEWER_PASSWORD = $envMap["DEMO_VIEWER_PASSWORD"]
  DEMO_TENANT_SLUG = if ($envMap.ContainsKey("DEMO_TENANT_SLUG")) { $envMap["DEMO_TENANT_SLUG"] } else { "demo" }
  REAL_SMS_ENABLED = "false"
  REAL_CALL_ENABLED = "false"
  REAL_EMAIL_ENABLED = "false"
  NODE_ENV = "production"
}
$apiOut = Join-Path $LogDir "api.out.log"
$apiErr = Join-Path $LogDir "api.err.log"
$pInfo = New-Object System.Diagnostics.ProcessStartInfo
$pInfo.FileName = (Get-Command node).Source
$pInfo.Arguments = "`"$(Join-Path $Root 'apps\api\dist\main.js')`""
$pInfo.WorkingDirectory = $Root
$pInfo.UseShellExecute = $false
$pInfo.RedirectStandardOutput = $true
$pInfo.RedirectStandardError = $true
foreach ($k in $apiEnv.Keys) { $pInfo.Environment[$k] = [string]$apiEnv[$k] }
$apiProc = New-Object System.Diagnostics.Process
$apiProc.StartInfo = $pInfo
$null = $apiProc.Start()
$apiProc.Id | Set-Content (Join-Path $RunDir "api.pid")
Start-Job -ScriptBlock { param($p,$f) while (-not $p.HasExited) { $l=$p.StandardOutput.ReadLine(); if ($null -ne $l) { Add-Content $f $l } } } -ArgumentList $apiProc,$apiOut | Out-Null
Start-Job -ScriptBlock { param($p,$f) while (-not $p.HasExited) { $l=$p.StandardError.ReadLine(); if ($null -ne $l) { Add-Content $f $l } } } -ArgumentList $apiProc,$apiErr | Out-Null

# --- Start gateway (web static + /api proxy) ---
Write-Host "Starting web gateway on 127.0.0.1:$WebPort ..."
$gwOut = Join-Path $LogDir "gateway.out.log"
$gwErr = Join-Path $LogDir "gateway.err.log"
$gInfo = New-Object System.Diagnostics.ProcessStartInfo
$gInfo.FileName = (Get-Command node).Source
$gInfo.Arguments = "`"$(Join-Path $Root 'deploy\public-gateway.mjs')`""
$gInfo.WorkingDirectory = $Root
$gInfo.UseShellExecute = $false
$gInfo.RedirectStandardOutput = $true
$gInfo.RedirectStandardError = $true
$gInfo.Environment["GATEWAY_HOST"] = "127.0.0.1"
$gInfo.Environment["GATEWAY_PORT"] = "$WebPort"
$gInfo.Environment["API_TARGET"] = "http://127.0.0.1:$ApiPort"
$gInfo.Environment["GATEWAY_WEB_MODE"] = "static"
$gwProc = New-Object System.Diagnostics.Process
$gwProc.StartInfo = $gInfo
$null = $gwProc.Start()
$gwProc.Id | Set-Content (Join-Path $RunDir "gateway.pid")

# --- Health gate ---
$healthUrl = "http://127.0.0.1:$WebPort/api/health"
$deadline = (Get-Date).AddSeconds(120)
$passed = $false
$lastBody = $null
$lastStatus = $null
Write-Host "Waiting for web /api/health (up to 120s): $healthUrl"
while ((Get-Date) -lt $deadline) {
  try {
    $resp = Invoke-WebRequest -Uri $healthUrl -UseBasicParsing -TimeoutSec 5 -ErrorAction Stop
    $lastStatus = [int]$resp.StatusCode
    $lastBody = [string]$resp.Content
    if ($lastStatus -ge 200 -and $lastStatus -lt 300 -and (Test-ApiHealthJson $lastBody)) {
      $passed = $true
      break
    }
  } catch {
    $lastBody = $_.Exception.Message
    $lastStatus = $null
  }
  Start-Sleep -Seconds 2
}

if ($passed) {
  Write-Host ""
  Write-Host "OK. Browser: http://127.0.0.1:$WebPort" -ForegroundColor Green
  Write-Host "Health gate passed: GET $healthUrl (ok + sales-os-api)"
  Write-Host "Demo emails: manager@demo.local / agent@demo.local / agent2@demo.local (passwords only in .env.native)"
  Write-Host "Stop: .\scripts\windows\native\Stop-InternalTrial-Native.ps1"
  exit 0
}

Write-Host ""
Write-Host "FAIL: api-or-db-not-ready — web /api/health gate did not pass within 120s" -ForegroundColor Red
Write-Host "URL: $healthUrl"
if ($null -ne $lastStatus) { Write-Host "Last HTTP: $lastStatus" } else { Write-Host "Last HTTP: (no response)" }
Write-Host "服务不可用。切勿当作已可用。"
exit 1
